## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Blythe ü§ç Radu"
theme = "hugo-story"


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "taxonomyTerm", "section"]
# googleAnalytics = "your-google-analytics-id"

assetDir = "static/"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "A (modular, highly tweakable) responsive one-page theme for Hugo"
  logo = "images/banner.jpg"
  favicon = true
